[project]
name = "lucio-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.74.0",
    "huggingface-hub>=0.36.2",
    "ipykernel>=7.2.0",
    "llama-cpp-python>=0.3.16",
    "orjson>=3.11.7",
    "sentence-transformers>=5.2.3",
    "transformers>=4.57.6",
]
